### ISSUE TITLE
Recommendation #1: A place for shields and custom AC

### ISSUE THREAD

**Issue by endeyequote** [wesbaker/roll20-character-sheets#38]
Hello, i've just started using your sheet and its pretty great. I do have a couple of recommendations though.

First: there is no place to put a shield. Shields dont set an AC rather they just give a bonus. So i a separate section for shields that calculates into your AC would be great. 

Also it would be great if there was a section you could input a bonus or penalty into AC that would calculate into the total AC to allow for custom rules, classes, and so on. 

Cheers!

**Comment by wesbaker** [comment]
> First: there is no place to put a shield. Shields dont set an AC rather they just give a bonus. So i a separate section for shields that calculates into your AC would be great.

All you need to do is click +Add under the armor area and add a shield, like so:

<img width="856" alt="Screen Shot 2020-07-17 at 11 28 04 AM" src="https://user-images.githubusercontent.com/15715/87803525-9571e700-c820-11ea-935a-943945209340.png">

> Also it would be great if there was a section you could input a bonus or penalty into AC that would calculate into the total AC to allow for custom rules, classes, and so on.

Hmm, I think this would be pretty rarely used. If I hear it come up a lot more, I'll try to think of somewhere to add it, but for now I'd recommend adding either "negative armor" or just a lower AC armor (sorta like cursed armor). So let's say you had a treant, and they get some crazy bonus to their HD, _but_ they're easier to hit because they're big. You could do something like this:

<img width="854" alt="Screen Shot 2020-07-17 at 11 31 50 AM" src="https://user-images.githubusercontent.com/15715/87803858-1c26c400-c821-11ea-8c68-c970a243df19.png">

**Comment by endeyequote** [comment]
Ah, i didnt realize it added armor values together, i thought it just set your AC to what your armor was then adjusted for DEX. Thanks!
