### ISSUE TITLE
Skill Rolls not working & Chat crashing 

### ISSUE THREAD

**Issue by endeyequote** [wesbaker/roll20-character-sheets#42]
When i try and roll skill rolls nothing happens. 

for example i have a skill set like this: 

Listen at Door / Roll 1d6 / VS < / Threshold 1 / Description: Exploration Skill

When i click on the roll button nothing happens, no roll, no roll chime.  

In addition, several times the sheet appears to have crashed the chat log and ive had to go into the game setting and clear it out to get it working again. 

Thanks for looking into it! Cheers.

**Comment by wesbaker** [comment]
> When i try and roll skill rolls nothing happens.

So I just tried this in my character sheet sandbox and it's working there (which includes changes that aren't live yet). My guess is the problem where the rolls look like black bars is causing that problem and it should be fixed tomorrow once Roll20 pushes up the fix. Please feel free to reopen this ticket if it's not fixed with that.
