### ISSUE TITLE
Spell level column values reset to 1

### ISSUE THREAD

**Issue by mattegger** [wesbaker/roll20-character-sheets#51]
Seems to accept any number for entry, but changes to 1 after a few seconds.

**Comment by Arraverz** [comment]
It seems this error occurs because the input for the spell level on line 564 in OSE-AAC.html has its type set to input
``` <input type="input" min="1" name="attr_spellLevel" value="1" /> ```

Changing that line to
``` <input type="number" min="1" name="attr_spellLevel" value="1" /> ```
will fix this issue.

I don't have a Roll20 Pro account to properly test this in the app, but using the Inspect Element feature to change the input type to number works.

**Comment by wesbaker** [comment]
Are either of you still having this problem? I'm not seeing this behavior at all. I am seeing that there's some weirdness in the width of the input though.

**Comment by Arraverz** [comment]
After the update the spell levels now save properly.
