### ISSUE TITLE
Incorrect Behavior w / Descending AC

### ISSUE THREAD

**Issue by BlankLink** [wesbaker/roll20-character-sheets#77]
When using descending AC, if you use a shield that gives a +1 bonus in your armor section, it adds it to your armour class, instead of subtracts it.

I.e. I have a 10 DEX, Leather Armor AC 7, and a shield AC +1, I should have an AC 6. Instead, I have an AC of 8. If I remove the shield by unchecking the 'worn' box, I return to an AC of 7.

**Comment by BlankLink** [comment]
Easily solved by typing the shields AC as -1, instead of +1, but thought you should know! Thanks for the work! It's a fantastic character sheet!

**Comment by wesbaker** [comment]
> Easily solved by typing the shields AC as -1, instead of +1,

It's been a while since I tinkered with this sheet, but I think I recall just going this route for DAC, mostly because I don't use DAC. I also think I'd have to do more work than I wanted to to invert the math. I'm going to be closing up my fork of the Roll20 sheets, but you're obviously welcome to make modifications and submit them to Roll20.
